### ISSUE TITLE
index original display date as string

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#144]
We currently parse the original date string from the article into number of millies since 01-JAN-1970. When displaying query results on the homepage or topic pages, this will be formatted as a date string again, which can lead to cases where the displayed date doesn't match the original date.

In order to always use the original date the author has defined, we should store it as a string in addition to the number and only use the latter in case the earlier is undefined.

cc @dominique-pfister @davidnuescheler

**Comment by tripodsan** [comment]
Either store it in epoch (millis since 1.1.1970 UTC) or as iso string **including** the timezone.
The problem occurs probably during the import, where the wrong timezone is assumed,
and probably during rendering, where again, the wrong timezone might be used.

But having a proper canonical date for sorting etc, is important.

**alternative**

In addition to the epoch time, also store a `displayTime` that is extracted during the import.  Since the importer imported all the articles with the same _wrong_ timezone, the existing field can still be used for sorting.

**Comment by rofe** [comment]
I think we can just pull the original date from the HTML doc and store it as an additional index property (keeping the timestamp for sorting, gating etc).

**Comment by kptdobe** [comment]
Which cases are still wrong ? I already spent several hours on the timezone issue (see https://github.com/adobe/theblog/issues/131) and I could not produce invalide dates (in the rendered page).
Parsing use UTC time: https://github.com/adobe/helix-index-pipelines/blob/c4840b9cf5868d4ca39050e030d052cc041a4e28/src/html_json.js#L22
Rendering use UTC time: https://github.com/adobe/theblog/blob/master/scripts.js#L125-L129

There should be no issue anymore ;)

**Comment by rofe** [comment]
@kptdobe I don't have any recent examples, maybe @davidnuescheler does...

Parsing and rendering in UTC is great, but since we are missing the exact time of publication and just assume 00:00, I think it could theoretically still happen that the displayed recalculated date does not match the text based one in the document itself.

Therefore it would just be safe to extract the original string and use that for display purposes, while still using the UTC millies for sorting and gating. 

wdyt?

**Comment by rofe** [comment]
> it could theoretically still happen 

... or not 😄

**Comment by rofe** [comment]
I think you're right, this probably isn't an issue anymore after all 😬 

One date related problem still remaining though is how we define "future" when we decide which posts to show. At the moment, we are using local time for that:
https://github.com/adobe/theblog/blob/master/scripts.js#L236-L237

Imagine the following use case: A Japanese author publishes a post at 6AM his time, and sets her local date, say 03-19-2020. It would only be 2PM for a reader on the west coast, and it would take that reader 10 hours to catch up and finally see the new post... not sure if that's intended? Maybe it would be wiser for now to just show all posts, regardless of their publication date, and later on think about how to deal with content that must show up at a very specific time (e.g. an earnings report).

**Comment by kptdobe** [comment]
Interestingly, all of this should be easy because we do not have to deal with... the exact time of publication: this is all about dates, no time. Wednesday the 18th is Wednesday the 18th all over the world.
The "make the post available at a specific time" is a new use case which I think would mean to introduce... the notion of publication time that we do not have.
