### ISSUE TITLE
Invalidate cache when content changes

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#32]

**Comment by dominique-pfister** [comment]
Content changes in OneDrive might be handled by using a combination of **webhook subscription** and **change tracking**:

**WebHook Subscription**
Documented [here](https://docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http), one can create a webhook pointing back to a public URL, that gets notified whenever a change occurs in the drive associated with theblog site. Note, that you won't get details about the *actual* change, though.

**Change Tracking**
Described [here](https://docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&tabs=http), one can then retrieve the changes since the last *delta*, which will include details about any items that were created, updated or deleted.

**Comment by tripodsan** [comment]
i think there should be generic re-index action, that can receive a list of URLs. In the worst case, this can be triggered manually.
the onedrive/googledoc change tracking should then invoke the respective re-indexers.

**Comment by davidnuescheler** [comment]
i removed the pitch label from this, as i think it may not be required in the short term, as manual invalidation or waiting for the timeout may be sufficient

**Comment by rofe** [comment]
@tripodsan reassigning this to you

**Comment by davidnuescheler** [comment]
i wonder if this is even desirable in the longer term (for this project). so i am still (kind of) supportive of this as a feature for helix pages but i think especially with a sharepoint backend i think we should close this issue for the blog project.
