### ISSUE TITLE
Scanner/Importer stopped working

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/theblog#330]
The scanner stopped working on August 4, no more articles are imported. Looking at Coralogix, one can see an error message appearing periodically when the trigger `five-mins-trigger` executes on `helix-clients`:
```
An error occured during the scan: . Error has been caught and next scan might solve the issue.
```
The message doesn't reveal much, but a manual invocation of the importer reveals an expired Azure Refresh Token.

**Comment by dominique-pfister** [comment]
I was unable to find the current secrets used in the scanner and importer, so I manually deployed 2 actions
- helix-theblog-scanner@debug
- helix-theblog-importer@debug

with valid credentials. 

I furthermore disable the current rule `/helix-clients/five-mins-scan` and created a new rule:
- /helix-clients/five-mins-scan-temporary

that invokes the "debug" scanner every 5 minutes as a temporary workaround.

A proper fix would consist in switching from refresh token to username/password based login in OneDrive, as in the `helix-onedrive-listener`: 

https://github.com/adobe/helix-onedrive-listener/blob/760ca95ea181a91622928c05468e0e414d6ca6d7/src/utils.js#L16

**Comment by kptdobe** [comment]
To solve this, here is what I have done:

For the scanner:

1. create a new refresh token with https://github.com/adobe/helix-onedrive-cli
1. update the token in CircleCi - https://app.circleci.com/settings/project/github/adobe/helix-theblog-scanner/environment-variables
1. trigger a new release with an empty commit `git commit --allow-empty -m "fix(ci): trigger a new clean release"`
1. delete the `/helix-clients/five-mins-scan-temporary`rule
1. re-enable the `/helix-clients/five-mins-scan` rule
1. create a follow up issue to use username / password (change does not seem trivial): see https://github.com/adobe/helix-theblog-scanner/issues/15

For the importer:
1. create a new refresh token with https://github.com/adobe/helix-onedrive-cli
1. update the token in CircleCi - https://app.circleci.com/settings/project/github/adobe/helix-theblog-importer/environment-variables
1. trigger a new release with an empty commit `git commit --allow-empty -m "fix(ci): trigger a new clean release"`
1. create a follow up issue to use username / password (change does not seem trivial): see https://github.com/adobe/helix-theblog-importer/issues/80

Since we might get rid of the importer sooner than later, not sure if this is worth changing the OneDrive login.

**Comment by kptdobe** [comment]
Seems to be back to normal.

**Comment by kptdobe** [comment]
Thanks @dominique-pfister for the tmp fix.
