### ISSUE TITLE
Image caption gets cut off on mobile device

### ISSUE THREAD

**Issue by kptdobe** [adobe/theblog#345]
Giselle shared the following: on a real mobile device (iphone XR in my case), open https://blog.adobe.com/en/2020/08/10/bringing-more-diverse-voices-to-the-world.html

![Image from iOS](https://user-images.githubusercontent.com/474200/89865527-32206e00-dbae-11ea-87a3-ad20fbb47c16.png)

Image caption gets cut off.

In fact, there is an horizontal scrollbar, you can still "scroll right" and see the full caption.

cc @rofe @davidnuescheler

**Comment by narcis-radu** [comment]
The image caption has `box-sizing: content-box` and `padding: 0 32px`; because of this, the total width will be 100% + 64px and horizontal scrolling will be introduced on the page. The fix is to set `box-sizing: border-box`, but I don't know how that will influence the recent changes added in #333 - @rofe @davidnuescheler.
@kptdobe - I can prepare a PR with the fix
