### ISSUE TITLE
Metadata description logic update needed (not to use the legend text)

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#363]
**Description**

- Some blogs posts are picking up a wrong description from the article
- We should not pick image legends for meta description
- the current ask it to pick up the first paragraph of the blog and add it to the description 

URL - https://blog.adobe.com/en/2020/08/10/bringing-more-diverse-voices-to-the-world.html#gs.d8u7k5

![image](https://user-images.githubusercontent.com/62259400/90025297-c819ce80-dc6a-11ea-8ef9-26f6a92d7eb4.png)

**Comment by rofe** [comment]
I'll try to improve the algorithm in helix Pages to better detect the first paragraph of "real" text.

Btw, shouldn't it be [Rose Marie Cromwell](http://www.rosemariecromwell.com/) rather than "Rose Marie Crowmwell"?

**Comment by rofe** [comment]
@avanishgandhi While checking a bunch of articles with hero captions to identify the best way forward here, and I found this particular example above to have a very long caption (10 words). And superfluous at that, too, since the image credits have also been baked into the hero image itself.

Since I couldn't find any other examples where accidental image credits ende up being the meta description so far, I'd be reluctant changing the algorithm until we have a better understanding of the problem or a more systemic solution in place (e.g. #366).

My proposal would be to instead shorten or remove the above caption to fix this particular problem.

**Comment by rofe** [comment]
![image](https://user-images.githubusercontent.com/1609742/91566960-ae53d900-e944-11ea-84d7-9669dffd2ce0.png)

**Comment by avanishgandhi** [comment]
I have asked Giselle the question and I am awaiting her response.

thanks

**Comment by avanishgandhi** [comment]
@rofe Gieselle confirmed that we can just remove the caption

**Comment by rofe** [comment]
Feel free to do so, of course. In any case, the original issue has been fixed now, and I'm closing this ticket.
