### ISSUE TITLE
Add region picker

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#419]
Basically revert https://github.com/adobe/theblog/pull/178/commits/9435f1f3696eb68ee5e2124e0e70b817a9a34aff

**Comment by rofe** [comment]
Not for batch-2, but batch-3 (regional blog migration)

**Comment by kptdobe** [comment]
There are some design changes, @avanishgandhi should provide more data.

**Comment by elaineskpt** [comment]
We had our grooming meeting today and  
We got the latest update for the designs. Will be starting tomorrow, but also checking what we will be adding via feds footer.
@kptdobe  @rofe

**Comment by kptdobe** [comment]
One thing which is not clear is how to handle the UK and APAC cases:
- `window.blog.language` gives you either `en`, `ko`, `de`...
- there is no specific "language" for the `/en/uk.html` or `/en/apac.html` page: in both cases, `window.blog.language` value is `en`.

This is only problematic to determine which "language" is currently checked in the region picker combo box. Here is a first solution:
- as soon as someone opens `/en/uk.html`, we add this info into the session storage - something like `sessionStorage.setItem('blog-regionPicker-language', 'en_uk');`
- as soon as someone opens `/en/apac.html`, we add this info into the session storage - something like `sessionStorage.setItem('blog-regionPicker-language', 'en_apac');`
- when trying to determine what is the current region, we first check if the sessionStorage contains an info: `sessionStorage.getItem('blog-regionPicker-language');`
- if the session storage gives uk or apac, it is the one to be selected in the combo. Otherwise use `window.blog.language`.

**Comment by rofe** [comment]
Implemented in February.
