### ISSUE TITLE
Serve all resources through the same domain to increase Lighthouse score

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#42]
The 2 Algolia libraries are currently served via 3rd party domains.

@trieloff can you help with that?

**Comment by davidnuescheler** [comment]
i think we should adopt all the client libraries into the project's scripts, so instead of loading existing convenience libs from a 3rd party host we should remove those dependencies and extract the things we need and commit the needed portions into our scripts in the repo...
i imagine some form a of `scripts.js` that includes all the necessary js, including `scrani.js` or alternatively split things up and use `defer` and `async` script.

**Comment by trieloff** [comment]
Other things to look at:
- [ ] typekit
- [ ] images from blob store

**Comment by davidnuescheler** [comment]
really, that's all it took?

<img width="501" alt="Screen Shot 2020-01-07 at 4 17 15 PM" src="https://user-images.githubusercontent.com/5289336/71937321-4fe5aa80-3169-11ea-9446-049e42b4ab46.png">

**Comment by rofe** [comment]
We are already serving images and typekit fonts through the same domain. Closing.
