### ISSUE TITLE
Consent widget design feedback

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#420]
Here's some design feedback on the new cookie consent widget now shown on blog.adobe.com:

![image](https://user-images.githubusercontent.com/1609742/92582647-7bd5a480-f291-11ea-9289-4a33173984bd.png)

#### Focus indicator

The widget replicates the styling of buttons used elsewhere on the site (i.e. on the homepage), but used a different, less refined focus indicator:

To see how the existing buttons on https://blog.adobe.com/ indicate focus, tab through to the "More on COVID-19" button. To reuse this styling, you can make them an `<a>` tag and assign the classes `action primary` to it (or see [here](https://github.com/adobe/theblog/blob/master/style.css#L177-L250) for the CSS).

#### Primary vs secondary

Speaking of primary vs secondary: I think "Enable All" - the quick & easy solution for the user - should have the `primary` class (and focus), and "Personalize" secondary.

### Maximum width

It seems like the widget maxes out at 1400px, which is somehwere in between the content (1200px) and the top nav (1440px). I would align it with either of the two.

**Comment by narcis-radu** [comment]
Hi @rofe,
The styling and functionality is managed by the OneTrust team and we should not override it.
**Focus indicator** - this is a known issue; we're tracking it under MWPW and OneTrust repo. I can provide the links to the issue if needed. You can reuse the focus styles, but this problem is visible on other pages and we'd like to fix it in the OneTrust code.
**Primary vs secondary** - I will take this feedback to Uma (via email).
**Maximum width** - I will take this feedback to Uma.

Thanks!

**Comment by rofe** [comment]
@narcis-radu any update from Uma?
