### ISSUE TITLE
geo detection and routing for blogs

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#503]
As per discussion on the 11/5 call, we want to configure blogs site with geo detection and routing to users coming from a region land the on the right language of blogs.

Below is the new language folder stucture.

![image](https://user-images.githubusercontent.com/62259400/98418729-6c2bcf80-2038-11eb-9ddf-78fbec145713.png)

**Comment by kptdobe** [comment]
I would add a dependency to https://github.com/adobe/theblog/issues/419: we should put automatic detection / routing only when the capability to switch the language is available. It is not because my browser is in German that I do not want to access the English version of the site!

**Comment by kptdobe** [comment]
Regarding implementation, my proposal is to:
- move `/index.docx` to `/en/index.docx`
- create `index.html` with only a piece of Javascript: 
  - if `navigator.language || navigator.userLanguage` is a known locale (`de`, `ko` as of today), redirect to `/de/` or `/ko/`. 
  - otherwise redirect to `/en/`

@rofe @davidnuescheler WDYT ?

**Comment by rofe** [comment]
I somehow have a feeling that a client side redirect on `/` isn't beneficial for SEO. But I don't have a better solution, so consider this my +0 😉

**Comment by trieloff** [comment]
We can do this redirect on the CDN, too. Just give me the spec and I'll set it's up.
