### ISSUE TITLE
Support for Meta data description authoring 

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#544]
- System should support addition of custom meta data description to blog pages
- System should support authoring of Metadata description for each blog articles
- System should support authoring of Metadata description for each Category page
- System should support authoring of Metadata description for each Home page
- Authors should be provided with an easy way to add meta data description to the word files. 
- If authors have added the metadata description then system will use that content to populate the meta data for pages; If there is no authored metadata, system will use the article content (please use the current logic as default content)

@rofe @kptdobe

**Comment by avanishgandhi** [comment]
this is duplicate ask with updated req from - https://github.com/adobe/theblog/issues/366

**Comment by rofe** [comment]
The metadata description can now be provided as a simple text paragraph/line underneath the title: 
![image](https://user-images.githubusercontent.com/1609742/104466603-b3dd5300-55b5-11eb-9bf1-298f178c6f30.png)

This text will not be displayed on the page, but will be used as the metadata description in the page source:

![image](https://user-images.githubusercontent.com/1609742/104466559-a7f19100-55b5-11eb-9577-11f96576e8fb.png)

__Note: The metadata description needs to have a minimum of 10 words, otherwise it will be skipped and the next larger paragraph will be used.__

Example page: https://staging--theblog--adobe.hlx.page/en/drafts/rofe/interlink.html

@avanishgandhi
